---
- name: zfs | add arter97 PPA for newer ZFS version
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ dev_zfs_ppa }}"
  
- name: zfs | dependencies zfsutils-linux
  apt:
    name: "{{ dev_zfs_dependencies }}"

- name: zfs | check pool existance
  command: zpool list -Ho name {{ item.pool }}
  register: result_pool_list
  ignore_errors: yes
  changed_when: false

- name: zfs | create pool
  command: >-
    zpool create
    {{ '-o' if item.options else '' }} {{ item.options | join(' -o ') }}
    {{ '-O' if item.bigOptions else '' }} {{ item.bigOptions | join(' -O ') }}
    {{ '-m ' + item.dest if item.dest else '' }}
    {{ item.pool }}
    {{ item.pool_mode | default('') }}
    {{ item.dev | join(' ') }}
  when:
    - item.pool_state | default('present') == 'present'
    - result_pool_list.rc == 1